config-version = 2

persistent-workspaces = [
    'k',
    'w',
    'c',
    't',
    'm',
    'a',
    's',
    '1',
    '2',
]

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

after-startup-command = [
    'exec-and-forget borders order=above active_color=0xff83a598 inactive_color=0xff1c1c1c width=2.0 hidpi=on',
    'exec-and-forget ${HOME}/.local/gitbin/aerospace-assign-workspaces',
    'exec-and-forget sketchybar',
    'exec-and-forget sketchybar-media',
]

on-focus-changed = [
  'exec-and-forget /bin/bash -c "sketchybar --trigger aerospace_focus_change PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"',
]

exec-on-workspace-change = [
  '/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       4
outer.bottom =     4
outer.right =      4
outer.top = [
  { monitor."EB321HQU" = 40 },
  { monitor."Acer CB241HY" = 40 },
  { monitor."Built-in Retina Display" = 8 },
  40,
]

[mode.main.binding]
    cmd-shift-z = 'close --quit-if-last-window'

    cmd-d = 'exec-and-forget ${HOME}/.local/gitbin/choose-app'

    cmd-h = 'focus left'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-l = 'focus right'

    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'

    cmd-ctrl-h = 'focus-monitor left'
    cmd-ctrl-j = 'workspace next --wrap-around'
    cmd-ctrl-k = 'workspace prev --wrap-around'
    cmd-ctrl-l = 'focus-monitor right'

    cmd-shift-ctrl-backslash = 'split horizontal'
    cmd-shift-ctrl-minus = 'split vertical'

    cmd-shift-f = 'fullscreen'

    alt-shift-space = 'layout floating tiling'

    cmd-q = 'workspace k'
    cmd-w = 'workspace w'
    cmd-e = 'workspace c'
    cmd-r = 'workspace t'
    cmd-1 = 'workspace m'
    cmd-2 = 'workspace s'
    cmd-3 = 'workspace 1'
    cmd-4 = 'workspace 2'
    cmd-backslash = 'workspace a'
    cmd-backspace = 'workspace-back-and-forth'

    cmd-alt-q = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap k'
    cmd-alt-w = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap w'
    cmd-alt-e = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap c'
    cmd-alt-r = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap t'
    cmd-alt-1 = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap m'
    cmd-alt-2 = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap s'
    cmd-alt-3 = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap 1'
    cmd-alt-4 = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap 2'
    cmd-alt-backslash = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-summon-swap a'

    cmd-ctrl-enter = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app Marta --launch'
    cmd-ctrl-z = 'exec-and-forget kitty -d ~'

    cmd-ctrl-q = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app k --launch k'
    cmd-ctrl-w = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app w --launch w'
    cmd-ctrl-e = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app c --launch c'
    cmd-ctrl-r = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app t --launch t'
    cmd-ctrl-1 = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app m --launch m'
    cmd-ctrl-2 = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app s --launch s'
    cmd-ctrl-backslash = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-focus-app a --launch a'

    cmd-shift-q = 'move-node-to-workspace k'
    cmd-shift-w = 'move-node-to-workspace w'
    cmd-shift-e = 'move-node-to-workspace c'
    cmd-shift-r = 'move-node-to-workspace t'
    cmd-shift-1 = 'move-node-to-workspace m'
    cmd-shift-2 = 'move-node-to-workspace s'
    cmd-shift-3 = 'move-node-to-workspace 1'
    cmd-shift-4 = 'move-node-to-workspace 2'
    cmd-shift-backslash = 'move-node-to-workspace a'

    cmd-shift-c = 'reload-config'
    cmd-shift-v = 'exec-and-forget ${HOME}/.local/gitbin/aerospace-assign-workspaces'
    cmd-shift-b = 'exec-and-forget /bin/bash -c "killall sketchybar; sketchybar"'

    cmd-shift-t = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = ['layout floating']

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    if.app-name-regex-substring = 'ChatGPT'
    run = ['move-node-to-workspace a']

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    if.app-name-regex-substring = 'ChatGPT'
    run = ['move-node-to-workspace a']

[[on-window-detected]]
    if.app-id = 'ch.laurinbrandner.nuage'
    run = ['move-node-to-workspace s']

[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = ['move-node-to-workspace s']

[[on-window-detected]]
    if.app-id = 'net.whatsapp.WhatsApp'
    run = ['move-node-to-workspace c']

[[on-window-detected]]
    if.app-id = 'org.whispersystems.signal-desktop'
    run = ['move-node-to-workspace c']
